$('document').ready(function(){
    $('div').mouseenter(function(){
        $('div').fadeTo('fast',1);
    })
});
$('document').ready(function(){
    $('div').mouseleave(function(){
        $('div').fadeTo('fast',.5);
    })
});